<?php
define("SITE_TITLE","Manager");
define("LOGIN_OK",0);
define("USER_NOT_FOUND",1);
define("PASSWORD_WRONG",2);
define("PASSWORD_NOT_MATCH",3);
define("NEW_USER_OK",4);
define("MAIL_ALREADY_USED",5);
define("MAIL_NOT_FOUND",6);
define("NEW_PASS_EMAIL",7);
define("IS_USER",2);
define("IS_ADMIN",1);
define("BAD",10);
define("GOOD",11);
